### ISSUE TITLE
Is this not support Visual Basic?

### ISSUE THREAD

**Issue by JasonHK** [Keboo/ShowMeTheXAML#3]
I found out that every time I compile my Visual Basic program, ShowMeTheXAML always generate C# file instead of Visual Basic in /obj/Debug folder. This makes unable to compile my program.

![screenshot 01885](https://user-images.githubusercontent.com/4410086/42631180-f5efc8ee-860b-11e8-916d-1537fca55d95.png)

**Comment by Keboo** [comment]
Currently no, there is not VB support. It would not be difficult to add, however I am not very familiar with VB. If you can show me what the expected VB syntax is for that file, I will look into adding VB support.

**Comment by FoxP** [comment]
```vbnet
Imports System.Collections.Generic

Namespace ShowMeTheXAML
    Module XamlDictionary
        Sub New()
        End Sub
    End Module
End Namespace
```

Don't hesitate to ask for tests.

**Comment by Keboo** [comment]
Visual Basic support is added in the 2.0.0 release
