### ISSUE TITLE
XamlDisplay not found

### ISSUE THREAD

**Issue by lanmanck** [Keboo/ShowMeTheXAML#4]
donot know how to use XamlDisplay.init(), it tips 'not found'

**Comment by Keboo** [comment]
Can you provide more information? 
Ensure you have the latest nuget package installed. [This](https://github.com/Keboo/ShowMeTheXAML/blob/master/ShowMeTheXAML/XamlDisplay.cs#L34-L54) is the method that needs to be invoked.

**Comment by lanmanck** [comment]
I'ver nuget newest package, in the code App.xaml.cs:
// for ShowMeTheXAML
        protected override void OnStartup(StartupEventArgs e)
        {
            XamlDisplay.Init();
            base.OnStartup(e);
        }
VS2017 says 'XamlDisplay' does not exist. Should I define it?

**Comment by Keboo** [comment]
@lanmanck you should not need to define it. Can you attach a sample project that shows the error?

**Comment by Keboo** [comment]
Closing for now. Let me know if there is still an issue here.
