### ISSUE TITLE
Use ShowMeTheXAML on child window view xaml code

### ISSUE THREAD

**Issue by Fengtao1314520** [Keboo/ShowMeTheXAML#6]
when i use ShowMeTheXAML and haven following code in App.xaml.cs
and i start my application and open child window, this window include `XamlDisplay` but the window dialog view xaml code

![2018-11-13_155912](https://user-images.githubusercontent.com/4384247/48399163-d23d2f00-e75d-11e8-8d03-34eb52812554.jpg)
the code

`
<smtx:XamlDisplay Key="ViewDesc" Margin="0,60,0,40">
<materialDesign:DialogHost Name="AddScriptToDevice" DialogOpened="AddScriptToDevice_OnDialogOpened" DialogClosing="AddScriptToDevice_OnDialogClosing" Style="{StaticResource MaterialDesignEmbeddedDialogHost}" DialogMargin="8">
<materialDesign:DialogHost.DialogContent>
</materialDesign:DialogHost.DialogContent>
<Border BorderThickness="1" BorderBrush="{DynamicResource PrimaryHueMidBrush}" MinWidth="256" MinHeight="256" ClipToBounds="True" Margin="0,0,-394,0">
<Grid Margin="0,0,0,0" Name="Includedg">
</Grid>
</Border>
</materialDesign:DialogHost>
</smtx:XamlDisplay>
`

**Comment by Keboo** [comment]
@Fengtao1314520 that looks like the expected behavior. What were wanting to make it look like?

**Comment by Fengtao1314520** [comment]
@Keboo  I want to show the dialog but actually shows the xaml code, I copy the MaterialDesignInXamlToolkit demo code to my project, and start my application, the actually dialog like the above image.

**Comment by Fengtao1314520** [comment]
@Keboo sorry , I already know where I went wrong.  i will close this issue.
 thanks for you
