### ISSUE TITLE
Strange transparent textbox under XamlDisplay

### ISSUE THREAD

**Issue by Leon-Zhang** [Keboo/ShowMeTheXAML#9]
I'm using following code to show a snackbar:
<smtx:XamlDisplay >
                        <materialDesign:Snackbar Message="hello 1" 
                                                 HorizontalAlignment="Stretch"
                                             IsActive="true"
                                             x:Name="SnackbarMsg" />
                    </smtx:XamlDisplay>

But a transparent textbox been added under XamlDisplay tree node:
![image](https://user-images.githubusercontent.com/2606646/59813082-25f2a500-934b-11e9-9ff5-3c20bbc0f375.png)

Anybody know why?

Thanks.

**Comment by Keboo** [comment]
@Leon-Zhang Are you actually using the XamlDisplay control to display XAML in your app? This control is only in the MaterialDesignInXaml Demo to make it easy for people to copy the XAML they need. You [should be able to omit it from your code](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#xamldisplay-control-issues).

**Comment by Leon-Zhang** [comment]
@Keboo Thanks for the answer! Removed XamlDisplay node and problem solved!
